### ISSUE TITLE
Problem running in docker

### ISSUE THREAD

**Issue by olanystrom** [PartiPirate/congressus#249]
`Fatal error: Uncaught Error: Call to a member function prepare() on null in /var/www/html/engine/bo/MotionBo.php:204 Stack trace: #0 /var/www/html/index.php(30): MotionBo->getByFilters(Array) #1 {main} thrown in /var/www/html/engine/bo/MotionBo.php on line 204`

**Comment by olanystrom** [comment]
Dockerfile
```
FROM php:7.4-apache
COPY application/ /var/www/html
EXPOSE 80
```
docker-compose.yml

```
version: '2'
services:
  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11212:11211"

  congressus:
    image: congressus:0
    ports:
      - "8301:80"
    volumes:
      - /home/admin/www/congressus/config:/var/www/html/config
    links:
      - memcached

```
